/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.actions;

import game.poker.holdem.dao.GameDaoImpl;
import game.poker.holdem.domain.Game;
import game.poker.holdem.domain.Player;
import game.poker.holdem.service.GameServiceImpl;

import javax.servlet.ServletException;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

public class GameAction extends Action {
	private String success = "";
	private String error = "";

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String reqCode = request.getParameter("reqCode");
//		try {
//			request.login("admin", "111");
//			System.out.println(request.getRemoteUser());
//		} catch (ServletException e) {
//			return new ActionRedirect("/login.html");
////			e.printStackTrace();
//		}
//		
		if(reqCode==null||reqCode.equalsIgnoreCase(""))
			reqCode = "goToLobby";
		if(reqCode.equalsIgnoreCase("joinAGame")){
			request.getRemoteUser();
			GameDaoImpl gamedao = new GameDaoImpl();
			long gameId = Long.parseLong(request.getParameter("gameId"));
			Game game = gamedao.findById(gameId, null);
			Player player = new Player();
			player.setGame(game);
			pl
//			player.setName(request.getRemoteUser());
//			player.setName(request.getParameter("playerName"));
			GameServiceImpl gameService = new GameServiceImpl();
//			player = gameService.addNewPlayerToGame(game, player);
			request.setAttribute("game", game);
		}
		return mapping.findForward(reqCode);
	}
}