/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package struts.actions;

import game.poker.holdem.dao.GameDaoImpl;
import game.poker.holdem.dao.PlayerDaoImpl;
import game.poker.holdem.domain.GameStructure;
import game.poker.holdem.domain.GameType;
import game.poker.holdem.domain.Player;
import game.poker.holdem.service.GameServiceImpl;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import common.game.poker.holdem.GameENT;

public class GameAction extends Action {
	private String success = "";
	private String error = "";

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		String reqCode = request.getParameter("reqCode");
		PlayerDaoImpl playerDaoImpl = new PlayerDaoImpl();
		GameDaoImpl gamedao = new GameDaoImpl();
		if (reqCode == null || reqCode.equalsIgnoreCase("")) {
			Player player = playerDaoImpl.findById(
					request.getRemoteUser(), null);
			request.setAttribute("player", player);
			request.setAttribute("games", gamedao.getAllGames(null));
			reqCode = "goToLobby";
		}
		if (reqCode.equalsIgnoreCase("joinAGame")) {
			long gameId = Long.parseLong(request.getParameter("gameId"));
			GameENT game = gamedao.findById(gameId, null);
			Player player = playerDaoImpl.findById(
					request.getRemoteUser(), null);
			if(game.getGameType().equals(GameType.CASH))
				reqCode = "goToCashGame";
//			player.setName(request.getParameter("nickname"));
			player = playerDaoImpl.merge(player, null);
//			GameServiceImpl gameService = new GameServiceImpl();
//			player = gameService.addNewPlayerToGame(game, player);
			request.setAttribute("game", game);
			request.setAttribute("player", player);
		}
		// startNewHand
		return mapping.findForward(reqCode);
	}
}